package:
  name: v2trim
  version: 1.1.0

source:
  git_url: https://github.com/aglabx/v2trim.git

requirements:
  run:
    - python
    - unzip
    - tar
    - gzip

test:
  commands:
    - v2trim -h

about:
  home: https://github.com/aglabx/v2trim
  license: GPLv2
  summary: 'Fast trimming of Illumina adapters'
